# Generated by Django 5.0.3 on 2024-04-02 12:51

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TimeLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('body', django_ckeditor_5.fields.CKEditor5Field()),
                ('month', models.DateField()),
            ],
        ),
    ]
